import { 
  Bot, 
  Sparkles, 
  Mic, 
  Video, 
  Brain, 
  BarChart3, 
  CheckCircle2, 
  FileText, 
  Clock,
  Target,
  Shield,
  MessageSquare
} from "lucide-react";
import { Link } from "react-router-dom";

import { Container } from "@/components/container";
import { Button } from "@/components/ui/button";

const ServicesPage = () => {
  const coreServices = [
    {
      icon: Brain,
      title: "AI-Generated Interview Questions",
      description: "Get personalized interview questions generated by advanced AI based on your job position, experience level, and technical requirements.",
      features: [
        "Customized to your job role",
        "5 questions per interview",
        "Technical and behavioral questions",
        "Industry-specific content"
      ]
    },
    {
      icon: Mic,
      title: "Voice Recording & Analysis",
      description: "Record your answers using your microphone. Our AI analyzes your speech patterns, clarity, and content quality.",
      features: [
        "Real-time speech-to-text",
        "Audio quality analysis",
        "Response length tracking",
        "Confidence level assessment"
      ]
    },
    {
      icon: Video,
      title: "Webcam Interview Simulation",
      description: "Practice with webcam enabled to simulate real interview conditions. Your privacy is protected - video is never recorded.",
      features: [
        "Real-time video preview",
        "Professional appearance tips",
        "Body language feedback",
        "Privacy guaranteed"
      ]
    },
    {
      icon: BarChart3,
      title: "Instant AI Feedback",
      description: "Receive comprehensive feedback immediately after each answer with ratings, strengths, and improvement suggestions.",
      features: [
        "Detailed performance ratings",
        "Strengths identification",
        "Areas for improvement",
        "Actionable recommendations"
      ]
    },
    {
      icon: FileText,
      title: "Interview History & Reports",
      description: "Track your progress over time with detailed reports of all your mock interviews and performance trends.",
      features: [
        "Complete interview history",
        "Performance analytics",
        "Progress tracking",
        "Exportable reports"
      ]
    },
    {
      icon: Target,
      title: "Custom Interview Creation",
      description: "Create unlimited mock interviews tailored to specific companies, roles, or technical stacks.",
      features: [
        "Unlimited interviews",
        "Multiple job positions",
        "Tech stack customization",
        "Experience level adjustment"
      ]
    }
  ];

  const useCases = [
    {
      title: "Technical Interviews",
      icon: Brain,
      description: "Prepare for coding interviews, system design, and technical problem-solving questions.",
      examples: [
        "Software Engineer positions",
        "Full Stack Developer roles",
        "Backend/Frontend Developer",
        "DevOps Engineer interviews"
      ],
      color: "bg-blue-50 border-blue-200"
    },
    {
      title: "Behavioral Interviews",
      icon: MessageSquare,
      description: "Practice answering behavioral questions about your experience, teamwork, and problem-solving.",
      examples: [
        "STAR method responses",
        "Leadership scenarios",
        "Conflict resolution",
        "Team collaboration stories"
      ],
      color: "bg-green-50 border-green-200"
    },
    {
      title: "Role-Specific Interviews",
      icon: Target,
      description: "Customize interviews for specific job roles and company requirements.",
      examples: [
        "Product Manager interviews",
        "Data Scientist positions",
        "UI/UX Designer roles",
        "Any custom job description"
      ],
      color: "bg-purple-50 border-purple-200"
    }
  ];

  const additionalFeatures = [
    {
      icon: Clock,
      title: "24/7 Availability",
      description: "Practice anytime, anywhere. No scheduling needed."
    },
    {
      icon: MessageSquare,
      title: "AI Support Chat",
      description: "Get instant help from our AI assistant whenever you need it."
    },
    {
      icon: Target,
      title: "Goal-Oriented Practice",
      description: "Set interview goals and track your progress toward achieving them."
    },
    {
      icon: Shield,
      title: "Privacy & Security",
      description: "Your data is secure. Video recordings are never stored."
    }
  ];

  return (
    <div className="flex-col w-full pb-24">
      <Container>
        {/* Header Section */}
        <div className="my-8 text-center">
          <h1 className="text-4xl md:text-6xl font-extrabold">
            Our <span className="text-primary">Services</span>
          </h1>
          <p className="mt-4 text-muted-foreground max-w-3xl mx-auto text-lg">
            Discover comprehensive AI-powered interview preparation services designed to help you excel in your next job interview. 
            From personalized question generation to detailed feedback, we provide everything you need to succeed.
          </p>

          {/* CTA Button */}
          <div className="flex justify-center mt-6">
            <Button
              asChild
              className="flex items-center gap-2 bg-primary text-white px-8 py-4 text-lg rounded-xl shadow-lg hover:bg-primary/90"
            >
              <Link to="/generate">
                <Sparkles className="w-5 h-5" /> Start Using Services
              </Link>
            </Button>
          </div>
        </div>

        {/* Core Services Section */}
        <div className="mt-16">
          <h2 className="text-3xl md:text-4xl font-bold text-center mb-12">
            Core <span className="text-primary">Services</span>
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {coreServices.map((service, index) => (
              <div
                key={index}
                className="bg-gray-50 p-6 rounded-lg shadow-md hover:shadow-lg transition-shadow"
              >
                <div className="bg-primary/10 p-3 rounded-full w-fit mb-4">
                  <service.icon className="w-6 h-6 text-primary" />
                </div>
                <h3 className="text-xl font-semibold mb-2">{service.title}</h3>
                <p className="text-muted-foreground mb-4">{service.description}</p>
                <ul className="space-y-2">
                  {service.features.map((feature, idx) => (
                    <li key={idx} className="flex items-start gap-2 text-sm">
                      <CheckCircle2 className="w-4 h-4 text-primary mt-0.5 flex-shrink-0" />
                      <span className="text-muted-foreground">{feature}</span>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </div>

        {/* Use Cases Section */}
        <div className="mt-16">
          <h2 className="text-3xl md:text-4xl font-bold text-center mb-4">
            Use <span className="text-primary">Cases</span>
          </h2>
          <p className="text-muted-foreground text-center mb-12 max-w-2xl mx-auto">
            Our AI Mock Interview platform supports various types of interviews and use cases to help you prepare for any scenario.
          </p>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {useCases.map((useCase, index) => (
              <div
                key={index}
                className={`${useCase.color} p-8 rounded-lg border-2 shadow-md hover:shadow-lg transition-shadow`}
              >
                <div className="bg-primary/10 p-4 rounded-full w-fit mb-4">
                  <useCase.icon className="w-8 h-8 text-primary" />
                </div>
                <h3 className="text-2xl font-bold mb-3">{useCase.title}</h3>
                <p className="text-muted-foreground mb-6">{useCase.description}</p>
                <div className="space-y-2">
                  <p className="font-semibold text-sm text-gray-700 mb-2">Examples:</p>
                  {useCase.examples.map((example, idx) => (
                    <div key={idx} className="flex items-start gap-2">
                      <CheckCircle2 className="w-4 h-4 text-primary mt-1 flex-shrink-0" />
                      <span className="text-sm text-muted-foreground">{example}</span>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Additional Features Section */}
        <div className="mt-16">
          <h2 className="text-3xl md:text-4xl font-bold text-center mb-12">
            Additional <span className="text-primary">Features</span>
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {additionalFeatures.map((feature, index) => (
              <div
                key={index}
                className="text-center p-6 bg-gradient-to-br from-gray-50 to-gray-100 rounded-lg shadow-md"
              >
                <div className="bg-primary/10 p-4 rounded-full w-fit mx-auto mb-4">
                  <feature.icon className="w-6 h-6 text-primary" />
                </div>
                <h3 className="text-lg font-semibold mb-2">{feature.title}</h3>
                <p className="text-muted-foreground text-sm">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Benefits Section */}
        <div className="mt-16 bg-gradient-to-r from-primary/10 to-primary/5 p-12 rounded-lg">
          <h2 className="text-3xl md:text-4xl font-bold text-center mb-8">
            Why Choose Our <span className="text-primary">Services</span>
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-4xl mx-auto">
            <div className="text-center">
              <div className="text-4xl font-bold text-primary mb-2">100%</div>
              <p className="text-muted-foreground">AI-Powered Analysis</p>
            </div>
            <div className="text-center">
              <div className="text-4xl font-bold text-primary mb-2">24/7</div>
              <p className="text-muted-foreground">Available Anytime</p>
            </div>
            <div className="text-center">
              <div className="text-4xl font-bold text-primary mb-2">Unlimited</div>
              <p className="text-muted-foreground">Mock Interviews</p>
            </div>
          </div>
        </div>

        {/* CTA Section */}
        <div className="mt-16 text-center">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            Ready to Improve Your Interview Skills?
          </h2>
          <p className="text-muted-foreground text-lg mb-8 max-w-2xl mx-auto">
            Start using our comprehensive AI-powered services today and take your interview preparation to the next level.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button
              asChild
              className="flex items-center gap-2 bg-primary text-white px-8 py-6 text-lg rounded-xl shadow-lg hover:bg-primary/90"
            >
              <Link to="/generate">
                <Sparkles className="w-5 h-5" /> Create Mock Interview
              </Link>
            </Button>
            <Button
              asChild
              variant="outline"
              className="flex items-center gap-2 px-8 py-6 text-lg rounded-xl"
            >
              <a
                href="https://www.messenger.com/t/754307874422696"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Bot className="w-5 h-5" /> Get AI Support
              </a>
            </Button>
          </div>
        </div>
      </Container>
    </div>
  );
};

export default ServicesPage;
